#! /usr/bin/env bash

java -jar ~/source/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i https://yser.p7m.de/v1/api/api.json -g rust -o . -p packageName=p7m-phone

git add src/
git add docs/
git restore .gitignore
git add .openapi-generator/FILES
git add README.md

echo
echo "**************************************************************"
echo "* Cargo.toml needs to be fixed and added to the staging area *"
echo "**************************************************************"
