/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.8
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_voicemail_qid`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVoicemailQidError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_voicemail_qid_vid`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVoicemailQidVidError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_voicemail_qid`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostVoicemailQidError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_voicemail_qid_vid`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutVoicemailQidVidError {
    Status404(),
    UnknownValue(serde_json::Value),
}


pub async fn get_voicemail_qid(configuration: &configuration::Configuration, qid: &str) -> Result<models::ListWrapperVoicemail, Error<GetVoicemailQidError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_qid = qid;

    let uri_str = format!("{}/voicemail/{qid}", configuration.base_path, qid=crate::apis::urlencode(p_qid));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListWrapperVoicemail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListWrapperVoicemail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVoicemailQidError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// This creates a/refreshes the signed_url to request the audio file if needed
pub async fn get_voicemail_qid_vid(configuration: &configuration::Configuration, qid: &str, vid: &str) -> Result<models::Voicemail, Error<GetVoicemailQidVidError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_qid = qid;
    let p_vid = vid;

    let uri_str = format!("{}/voicemail/{qid}/{vid}", configuration.base_path, qid=crate::apis::urlencode(p_qid), vid=crate::apis::urlencode(p_vid));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Voicemail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Voicemail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVoicemailQidVidError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn post_voicemail_qid(configuration: &configuration::Configuration, qid: &str, new_voicemail: models::NewVoicemail) -> Result<models::Voicemail, Error<PostVoicemailQidError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_qid = qid;
    let p_new_voicemail = new_voicemail;

    let uri_str = format!("{}/voicemail/{qid}", configuration.base_path, qid=crate::apis::urlencode(p_qid));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_new_voicemail);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Voicemail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Voicemail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostVoicemailQidError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn put_voicemail_qid_vid(configuration: &configuration::Configuration, qid: &str, vid: &str, voicemail_update: models::VoicemailUpdate) -> Result<models::Voicemail, Error<PutVoicemailQidVidError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_qid = qid;
    let p_vid = vid;
    let p_voicemail_update = voicemail_update;

    let uri_str = format!("{}/voicemail/{qid}/{vid}", configuration.base_path, qid=crate::apis::urlencode(p_qid), vid=crate::apis::urlencode(p_vid));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_voicemail_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Voicemail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Voicemail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PutVoicemailQidVidError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

