/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.5.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlarmCallUpdate {
    #[serde(rename = "callState")]
    pub call_state: models::AlarmCallState,
    #[serde(rename = "pressedDigit")]
    pub pressed_digit: String,
}

impl AlarmCallUpdate {
    pub fn new(call_state: models::AlarmCallState, pressed_digit: String) -> AlarmCallUpdate {
        AlarmCallUpdate {
            call_state,
            pressed_digit,
        }
    }
}

