/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Block {
    #[serde(rename = "block_id")]
    pub block_id: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: String,
    #[serde(rename = "queue_id")]
    pub queue_id: String,
    #[serde(rename = "start_time")]
    pub start_time: String,
    #[serde(rename = "end_time")]
    pub end_time: String,
    #[serde(rename = "announce")]
    pub announce: String,
    #[serde(rename = "started", skip_serializing_if = "Option::is_none")]
    pub started: Option<String>,
    #[serde(rename = "ended", skip_serializing_if = "Option::is_none")]
    pub ended: Option<String>,
    #[serde(rename = "started2", skip_serializing_if = "Option::is_none")]
    pub started2: Option<String>,
    #[serde(rename = "ended2", skip_serializing_if = "Option::is_none")]
    pub ended2: Option<String>,
}

impl Block {
    pub fn new(block_id: String, tenant_id: String, queue_id: String, start_time: String, end_time: String, announce: String) -> Block {
        Block {
            block_id,
            tenant_id,
            queue_id,
            start_time,
            end_time,
            announce,
            started: None,
            ended: None,
            started2: None,
            ended2: None,
        }
    }
}


