/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.5.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CallState {
    #[serde(rename = "Entering")]
    Entering,
    #[serde(rename = "AnnounceLimit")]
    AnnounceLimit,
    #[serde(rename = "Waiting")]
    Waiting,
    #[serde(rename = "Ringing")]
    Ringing,
    #[serde(rename = "Connected")]
    Connected,

}

impl std::fmt::Display for CallState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Entering => write!(f, "Entering"),
            Self::AnnounceLimit => write!(f, "AnnounceLimit"),
            Self::Waiting => write!(f, "Waiting"),
            Self::Ringing => write!(f, "Ringing"),
            Self::Connected => write!(f, "Connected"),
        }
    }
}

impl Default for CallState {
    fn default() -> CallState {
        Self::Entering
    }
}

