/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegacyQueue {
    #[serde(rename = "queue_id")]
    pub queue_id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "queue")]
    pub queue: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl LegacyQueue {
    pub fn new(queue_id: uuid::Uuid, tenant_id: uuid::Uuid, queue: String, name: String) -> LegacyQueue {
        LegacyQueue {
            queue_id,
            tenant_id,
            queue,
            name,
        }
    }
}

