/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListWrapperQueueCallerDataInner : This represents a caller in a waiting queue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWrapperQueueCallerDataInner {
    /// ID of this caller in the queue
    #[serde(rename = "queueCallerId")]
    pub queue_caller_id: uuid::Uuid,
    /// The tenant this call belongs to
    #[serde(rename = "tenantId")]
    pub tenant_id: uuid::Uuid,
    /// The queue this call is on
    #[serde(rename = "queueId")]
    pub queue_id: uuid::Uuid,
    /// The number of the queue that has been called
    #[serde(rename = "queueNumberId")]
    pub queue_number_id: uuid::Uuid,
    /// CLIP of the call if known
    #[serde(rename = "callerNumber")]
    pub caller_number: String,
    /// Priority in the queue (higher number is higher priority)
    #[serde(rename = "prio")]
    pub prio: i32,
    /// The state of this call
    #[serde(rename = "callState")]
    pub call_state: models::CallState,
    /// If set, this call should ring until this timestamp
    #[serde(rename = "ringUntil", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ring_until: Option<Option<String>>,
    /// When the incoming call started
    #[serde(rename = "startTime")]
    pub start_time: String,
    /// When this structure has been updated the last time
    #[serde(rename = "lastChange")]
    pub last_change: String,
    /// When the REST caller should check the next time for changed states
    #[serde(rename = "nextCheck")]
    pub next_check: String,
}

impl ListWrapperQueueCallerDataInner {
    /// This represents a caller in a waiting queue
    pub fn new(queue_caller_id: uuid::Uuid, tenant_id: uuid::Uuid, queue_id: uuid::Uuid, queue_number_id: uuid::Uuid, caller_number: String, prio: i32, call_state: models::CallState, start_time: String, last_change: String, next_check: String) -> ListWrapperQueueCallerDataInner {
        ListWrapperQueueCallerDataInner {
            queue_caller_id,
            tenant_id,
            queue_id,
            queue_number_id,
            caller_number,
            prio,
            call_state,
            ring_until: None,
            start_time,
            last_change,
            next_check,
        }
    }
}

