/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.4
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWrapperVoicemailDataInner {
    #[serde(rename = "voicemail_id")]
    pub voicemail_id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "queue_id")]
    pub queue_id: uuid::Uuid,
    #[serde(rename = "caller")]
    pub caller: String,
    #[serde(rename = "topic")]
    pub topic: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "last_change")]
    pub last_change: String,
}

impl ListWrapperVoicemailDataInner {
    pub fn new(voicemail_id: uuid::Uuid, tenant_id: uuid::Uuid, queue_id: uuid::Uuid, caller: String, topic: String, message: String, timestamp: String, last_change: String) -> ListWrapperVoicemailDataInner {
        ListWrapperVoicemailDataInner {
            voicemail_id,
            tenant_id,
            queue_id,
            caller,
            topic,
            message,
            timestamp,
            last_change,
        }
    }
}

