/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewQueueNumber {
    #[serde(rename = "number")]
    pub number: String,
    #[serde(rename = "prio")]
    pub prio: i32,
    #[serde(rename = "forcedCallerName")]
    pub forced_caller_name: String,
}

impl NewQueueNumber {
    pub fn new(number: String, prio: i32, forced_caller_name: String) -> NewQueueNumber {
        NewQueueNumber {
            number,
            prio,
            forced_caller_name,
        }
    }
}

