/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.7
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewVoicemail {
    #[serde(rename = "caller")]
    pub caller: String,
    #[serde(rename = "topic")]
    pub topic: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "audio_filename")]
    pub audio_filename: String,
    #[serde(rename = "audio_s3_path")]
    pub audio_s3_path: String,
}

impl NewVoicemail {
    pub fn new(caller: String, topic: String, message: String, channel: String, language: String, audio_filename: String, audio_s3_path: String) -> NewVoicemail {
        NewVoicemail {
            caller,
            topic,
            message,
            channel,
            language,
            audio_filename,
            audio_s3_path,
        }
    }
}

