/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewAlarmCall {
    #[serde(rename = "alarmId")]
    pub alarm_id: uuid::Uuid,
    #[serde(rename = "callee")]
    pub callee: String,
    #[serde(rename = "callText")]
    pub call_text: String,
    #[serde(rename = "callbackText")]
    pub callback_text: String,
    #[serde(rename = "callAcceptedDigits")]
    pub call_accepted_digits: String,
    #[serde(rename = "callbackAcceptedDigits")]
    pub callback_accepted_digits: String,
    #[serde(rename = "dummy")]
    pub dummy: bool,
}

impl NewAlarmCall {
    pub fn new(alarm_id: uuid::Uuid, callee: String, call_text: String, callback_text: String, call_accepted_digits: String, callback_accepted_digits: String, dummy: bool) -> NewAlarmCall {
        NewAlarmCall {
            alarm_id,
            callee,
            call_text,
            callback_text,
            call_accepted_digits,
            callback_accepted_digits,
            dummy,
        }
    }
}

