/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.6.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewQueueCaller {
    #[serde(rename = "queueNumberId")]
    pub queue_number_id: uuid::Uuid,
    #[serde(rename = "callerNumber")]
    pub caller_number: String,
    #[serde(rename = "prio")]
    pub prio: i32,
    #[serde(rename = "ringRequest")]
    pub ring_request: bool,
    #[serde(rename = "startTime")]
    pub start_time: String,
}

impl NewQueueCaller {
    pub fn new(queue_number_id: uuid::Uuid, caller_number: String, prio: i32, ring_request: bool, start_time: String) -> NewQueueCaller {
        NewQueueCaller {
            queue_number_id,
            caller_number,
            prio,
            ring_request,
            start_time,
        }
    }
}

