/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewBlock {
    #[serde(rename = "queue_id")]
    pub queue_id: uuid::Uuid,
    #[serde(rename = "start_time")]
    pub start_time: String,
    #[serde(rename = "end_time")]
    pub end_time: String,
    #[serde(rename = "announce")]
    pub announce: String,
}

impl NewBlock {
    pub fn new(queue_id: uuid::Uuid, start_time: String, end_time: String, announce: String) -> NewBlock {
        NewBlock {
            queue_id,
            start_time,
            end_time,
            announce,
        }
    }
}

