/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewQueueNumber : Data required to add a new number to a queue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewQueueNumber {
    /// The phone number in E.164 format including a '+' prefix
    #[serde(rename = "number")]
    pub number: String,
    /// The priority calls on this number get assigned by default
    #[serde(rename = "prio")]
    pub prio: i32,
    /// Set this as the name of the caller when ringing the destinations (empty to not force a caller name)
    #[serde(rename = "forcedCallerName")]
    pub forced_caller_name: String,
}

impl NewQueueNumber {
    /// Data required to add a new number to a queue
    pub fn new(number: String, prio: i32, forced_caller_name: String) -> NewQueueNumber {
        NewQueueNumber {
            number,
            prio,
            forced_caller_name,
        }
    }
}

