/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewQueueDestination : Update to a destination
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewQueueDestination {
    /// Minimum priority a call needs to get signalled on this destination
    #[serde(rename = "prioMin")]
    pub prio_min: i32,
    /// Maximum priority a call can have to get signalled on this destination
    #[serde(rename = "prioMax")]
    pub prio_max: i32,
    /// Phone number where to ring (E.164 format including '+' prefix)
    #[serde(rename = "destination")]
    pub destination: String,
    /// Name of this destination for representation on the UI
    #[serde(rename = "description")]
    pub description: String,
}

impl NewQueueDestination {
    /// Update to a destination
    pub fn new(prio_min: i32, prio_max: i32, destination: String, description: String) -> NewQueueDestination {
        NewQueueDestination {
            prio_min,
            prio_max,
            destination,
            description,
        }
    }
}

