/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.7
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhoneNumber {
    #[serde(rename = "e164")]
    pub e164: String,
    #[serde(rename = "international")]
    pub international: String,
    #[serde(rename = "national")]
    pub national: String,
    #[serde(rename = "country_code")]
    pub country_code: String,
}

impl PhoneNumber {
    pub fn new(e164: String, international: String, national: String, country_code: String) -> PhoneNumber {
        PhoneNumber {
            e164,
            international,
            national,
            country_code,
        }
    }
}

