/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.6.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueNumber {
    #[serde(rename = "queueNumberId")]
    pub queue_number_id: uuid::Uuid,
    #[serde(rename = "tenantId")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "number")]
    pub number: String,
    #[serde(rename = "queueId")]
    pub queue_id: uuid::Uuid,
    #[serde(rename = "prio")]
    pub prio: i32,
    #[serde(rename = "forcedCallerName")]
    pub forced_caller_name: String,
    #[serde(rename = "lastChange")]
    pub last_change: String,
}

impl QueueNumber {
    pub fn new(queue_number_id: uuid::Uuid, tenant_id: uuid::Uuid, number: String, queue_id: uuid::Uuid, prio: i32, forced_caller_name: String, last_change: String) -> QueueNumber {
        QueueNumber {
            queue_number_id,
            tenant_id,
            number,
            queue_id,
            prio,
            forced_caller_name,
            last_change,
        }
    }
}

