/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QueueCall {
    #[serde(rename = "state")]
    pub state: crate::models::CallState,
    #[serde(rename = "caller_id_num", skip_serializing_if = "Option::is_none")]
    pub caller_id_num: Option<String>,
    #[serde(rename = "caller_id_name", skip_serializing_if = "Option::is_none")]
    pub caller_id_name: Option<String>,
    #[serde(rename = "call_time")]
    pub call_time: String,
    #[serde(rename = "wait_time")]
    pub wait_time: String,
    #[serde(rename = "talk_time", skip_serializing_if = "Option::is_none")]
    pub talk_time: Option<String>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i64>,
    #[serde(rename = "unique_id")]
    pub unique_id: String,
    #[serde(rename = "queue_pos", skip_serializing_if = "Option::is_none")]
    pub queue_pos: Option<i64>,
    #[serde(rename = "from_caller_jitter", skip_serializing_if = "Option::is_none")]
    pub from_caller_jitter: Option<String>,
    #[serde(rename = "from_caller_cumulative_lost", skip_serializing_if = "Option::is_none")]
    pub from_caller_cumulative_lost: Option<String>,
    #[serde(rename = "from_caller_fraction_lost", skip_serializing_if = "Option::is_none")]
    pub from_caller_fraction_lost: Option<String>,
    #[serde(rename = "to_caller_jitter", skip_serializing_if = "Option::is_none")]
    pub to_caller_jitter: Option<String>,
    #[serde(rename = "to_caller_cumulative_lost", skip_serializing_if = "Option::is_none")]
    pub to_caller_cumulative_lost: Option<String>,
    #[serde(rename = "to_caller_fraction_lost", skip_serializing_if = "Option::is_none")]
    pub to_caller_fraction_lost: Option<String>,
    #[serde(rename = "from_agent_jitter", skip_serializing_if = "Option::is_none")]
    pub from_agent_jitter: Option<String>,
    #[serde(rename = "from_agent_cumulative_lost", skip_serializing_if = "Option::is_none")]
    pub from_agent_cumulative_lost: Option<String>,
    #[serde(rename = "from_agent_fraction_lost", skip_serializing_if = "Option::is_none")]
    pub from_agent_fraction_lost: Option<String>,
    #[serde(rename = "to_agent_jitter", skip_serializing_if = "Option::is_none")]
    pub to_agent_jitter: Option<String>,
    #[serde(rename = "to_agent_cumulative_lost", skip_serializing_if = "Option::is_none")]
    pub to_agent_cumulative_lost: Option<String>,
    #[serde(rename = "to_agent_fraction_lost", skip_serializing_if = "Option::is_none")]
    pub to_agent_fraction_lost: Option<String>,
}

impl QueueCall {
    pub fn new(state: crate::models::CallState, call_time: String, wait_time: String, unique_id: String) -> QueueCall {
        QueueCall {
            state,
            caller_id_num: None,
            caller_id_name: None,
            call_time,
            wait_time,
            talk_time: None,
            priority: None,
            unique_id,
            queue_pos: None,
            from_caller_jitter: None,
            from_caller_cumulative_lost: None,
            from_caller_fraction_lost: None,
            to_caller_jitter: None,
            to_caller_cumulative_lost: None,
            to_caller_fraction_lost: None,
            from_agent_jitter: None,
            from_agent_cumulative_lost: None,
            from_agent_fraction_lost: None,
            to_agent_jitter: None,
            to_agent_cumulative_lost: None,
            to_agent_fraction_lost: None,
        }
    }
}


