/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Queue {
    #[serde(rename = "queue_id")]
    pub queue_id: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: String,
    #[serde(rename = "queue")]
    pub queue: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl Queue {
    pub fn new(queue_id: String, tenant_id: String, queue: String, name: String) -> Queue {
        Queue {
            queue_id,
            tenant_id,
            queue,
            name,
        }
    }
}


