/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.5.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Queue {
    #[serde(rename = "queueId")]
    pub queue_id: uuid::Uuid,
    #[serde(rename = "tenantId")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "queueToken")]
    pub queue_token: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "timezone")]
    pub timezone: String,
    #[serde(rename = "prio")]
    pub prio: Vec<models::QueuePrio>,
    #[serde(rename = "lastChange")]
    pub last_change: String,
}

impl Queue {
    pub fn new(queue_id: uuid::Uuid, tenant_id: uuid::Uuid, queue_token: String, name: String, timezone: String, prio: Vec<models::QueuePrio>, last_change: String) -> Queue {
        Queue {
            queue_id,
            tenant_id,
            queue_token,
            name,
            timezone,
            prio,
            last_change,
        }
    }
}

