/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.4
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoicemailUpdate {
    #[serde(rename = "update_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub update_message: Option<Option<bool>>,
    #[serde(rename = "update_done", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub update_done: Option<Option<bool>>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "done_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub done_at: Option<Option<String>>,
}

impl VoicemailUpdate {
    pub fn new(message: String) -> VoicemailUpdate {
        VoicemailUpdate {
            update_message: None,
            update_done: None,
            message,
            done_at: None,
        }
    }
}

