/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.7.7
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Voicemail {
    #[serde(rename = "voicemail_id")]
    pub voicemail_id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "queue_id")]
    pub queue_id: uuid::Uuid,
    #[serde(rename = "caller")]
    pub caller: String,
    #[serde(rename = "caller_phone_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub caller_phone_number: Option<Option<Box<models::PhoneNumber>>>,
    #[serde(rename = "topic")]
    pub topic: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "done_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub done_at: Option<Option<String>>,
    #[serde(rename = "done_by", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub done_by: Option<Option<uuid::Uuid>>,
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "audio_filename")]
    pub audio_filename: String,
    #[serde(rename = "signed_url")]
    pub signed_url: String,
    #[serde(rename = "url_valid_to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url_valid_to: Option<Option<String>>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "last_change")]
    pub last_change: String,
}

impl Voicemail {
    pub fn new(voicemail_id: uuid::Uuid, tenant_id: uuid::Uuid, queue_id: uuid::Uuid, caller: String, topic: String, message: String, language: String, audio_filename: String, signed_url: String, timestamp: String, last_change: String) -> Voicemail {
        Voicemail {
            voicemail_id,
            tenant_id,
            queue_id,
            caller,
            caller_phone_number: None,
            topic,
            message,
            done_at: None,
            done_by: None,
            language,
            audio_filename,
            signed_url,
            url_valid_to: None,
            timestamp,
            last_change,
        }
    }
}

