/*
 * Phone and Queue Backend
 *
 * API for managing phone services  This is the API of the service at P7M that manages phone services.  **Attention:** this API will probably still change a lot in the future, it's not at all stable yet
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WeekdayHoliday {
    #[serde(rename = "MONDAY")]
    MONDAY,
    #[serde(rename = "TUESDAY")]
    TUESDAY,
    #[serde(rename = "WEDNESDAY")]
    WEDNESDAY,
    #[serde(rename = "THURSDAY")]
    THURSDAY,
    #[serde(rename = "FRIDAY")]
    FRIDAY,
    #[serde(rename = "SATURDAY")]
    SATURDAY,
    #[serde(rename = "SUNDAY")]
    SUNDAY,
    #[serde(rename = "HOLIDAY")]
    HOLIDAY,

}

impl ToString for WeekdayHoliday {
    fn to_string(&self) -> String {
        match self {
            Self::MONDAY => String::from("MONDAY"),
            Self::TUESDAY => String::from("TUESDAY"),
            Self::WEDNESDAY => String::from("WEDNESDAY"),
            Self::THURSDAY => String::from("THURSDAY"),
            Self::FRIDAY => String::from("FRIDAY"),
            Self::SATURDAY => String::from("SATURDAY"),
            Self::SUNDAY => String::from("SUNDAY"),
            Self::HOLIDAY => String::from("HOLIDAY"),
        }
    }
}

impl Default for WeekdayHoliday {
    fn default() -> WeekdayHoliday {
        Self::MONDAY
    }
}




